
# This default profile is used when running a single instance completely standalone:
spring:
  profiles: default
server:
  port: 8761  
eureka:
  instance:
    hostname: localhost  
  client:
    registerWithEureka: false
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/  #dynamic host and port